# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anketa_page_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnketaPageWindow(object):
    def setupUi(self, AnketaPageWindow):
        AnketaPageWindow.setObjectName("AnketaPageWindow")
        AnketaPageWindow.resize(1100, 900)
        AnketaPageWindow.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.logo = QtWidgets.QLabel(AnketaPageWindow)
        self.logo.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo.setObjectName("logo")
        self.logo_icon = QtWidgets.QLabel(AnketaPageWindow)
        self.logo_icon.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon.setObjectName("logo_icon")
        self.widget = QtWidgets.QWidget(AnketaPageWindow)
        self.widget.setGeometry(QtCore.QRect(175, 210, 750, 500))
        self.widget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget.setObjectName("widget")
        self.anketa_word = QtWidgets.QLabel(self.widget)
        self.anketa_word.setGeometry(QtCore.QRect(285, 20, 180, 40))
        self.anketa_word.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.anketa_word.setAlignment(QtCore.Qt.AlignCenter)
        self.anketa_word.setObjectName("anketa_word")
        self.firstname = QtWidgets.QLineEdit(self.widget)
        self.firstname.setGeometry(QtCore.QRect(265, 160, 350, 40))
        self.firstname.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.firstname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.firstname.setObjectName("firstname")
        self.surname = QtWidgets.QLineEdit(self.widget)
        self.surname.setGeometry(QtCore.QRect(265, 220, 350, 40))
        self.surname.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.surname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.surname.setObjectName("surname")
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setGeometry(QtCore.QRect(130, 330, 490, 50))
        self.error_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.save_button = QtWidgets.QPushButton(self.widget)
        self.save_button.setGeometry(QtCore.QRect(305, 420, 140, 40))
        self.save_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.save_button.setObjectName("save_button")
        self.anketa_icon = QtWidgets.QLabel(self.widget)
        self.anketa_icon.setGeometry(QtCore.QRect(125, 160, 110, 160))
        self.anketa_icon.setObjectName("anketa_icon")
        self.info_label = QtWidgets.QLabel(self.widget)
        self.info_label.setGeometry(QtCore.QRect(100, 70, 550, 30))
        self.info_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.total_income = QtWidgets.QLineEdit(self.widget)
        self.total_income.setGeometry(QtCore.QRect(265, 280, 350, 40))
        self.total_income.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.total_income.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.total_income.setObjectName("total_income")

        self.retranslateUi(AnketaPageWindow)
        QtCore.QMetaObject.connectSlotsByName(AnketaPageWindow)

    def retranslateUi(self, AnketaPageWindow):
        _translate = QtCore.QCoreApplication.translate
        AnketaPageWindow.setWindowTitle(_translate("AnketaPageWindow", "BudgetKeeper"))
        self.logo.setText(_translate("AnketaPageWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.logo_icon.setText(_translate("AnketaPageWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
        self.anketa_word.setText(_translate("AnketaPageWindow", "Анкета"))
        self.firstname.setPlaceholderText(_translate("AnketaPageWindow", " имя"))
        self.surname.setPlaceholderText(_translate("AnketaPageWindow", " фамилия"))
        self.save_button.setText(_translate("AnketaPageWindow", "Сохранить"))
        self.anketa_icon.setText(_translate("AnketaPageWindow", "<html><head/><body><p><img src=\":/icons/anketa_icon.png\"/></p></body></html>"))
        self.info_label.setText(_translate("AnketaPageWindow", "Твои данные помогут нам настроить приложение именно под тебя"))
        self.total_income.setPlaceholderText(_translate("AnketaPageWindow", " текущий доход"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnketaPageWindow = QtWidgets.QWidget()
    ui = Ui_AnketaPageWindow()
    ui.setupUi(AnketaPageWindow)
    AnketaPageWindow.show()
    sys.exit(app.exec_())
