# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_delete_account_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmDeleteWindow(object):
    def setupUi(self, ConfirmDeleteWindow):
        ConfirmDeleteWindow.setObjectName("ConfirmDeleteWindow")
        ConfirmDeleteWindow.resize(500, 170)
        ConfirmDeleteWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.confirm_label = QtWidgets.QLabel(ConfirmDeleteWindow)
        self.confirm_label.setGeometry(QtCore.QRect(75, 30, 350, 20))
        self.confirm_label.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setObjectName("confirm_label")
        self.yes_button = QtWidgets.QPushButton(ConfirmDeleteWindow)
        self.yes_button.setGeometry(QtCore.QRect(135, 80, 100, 40))
        self.yes_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QPushButton(ConfirmDeleteWindow)
        self.no_button.setGeometry(QtCore.QRect(265, 80, 100, 40))
        self.no_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.no_button.setObjectName("no_button")

        self.retranslateUi(ConfirmDeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmDeleteWindow)

    def retranslateUi(self, ConfirmDeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmDeleteWindow.setWindowTitle(_translate("ConfirmDeleteWindow", "BudgetKeeper"))
        self.confirm_label.setText(_translate("ConfirmDeleteWindow", "Ты точно хочешь удалить счёт?"))
        self.yes_button.setText(_translate("ConfirmDeleteWindow", "Да"))
        self.no_button.setText(_translate("ConfirmDeleteWindow", "Нет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmDeleteWindow = QtWidgets.QWidget()
    ui = Ui_ConfirmDeleteWindow()
    ui.setupUi(ConfirmDeleteWindow)
    ConfirmDeleteWindow.show()
    sys.exit(app.exec_())
