# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_password_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmPasswordWindow(object):
    def setupUi(self, ConfirmPasswordWindow):
        ConfirmPasswordWindow.setObjectName("ConfirmPasswordWindow")
        ConfirmPasswordWindow.resize(500, 270)
        ConfirmPasswordWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.error_label = QtWidgets.QLabel(ConfirmPasswordWindow)
        self.error_label.setGeometry(QtCore.QRect(70, 120, 350, 50))
        self.error_label.setStyleSheet("color: rgb(181, 131, 141);\n"
"font: 12pt \"Involve\";")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.confirm_label = QtWidgets.QLabel(ConfirmPasswordWindow)
        self.confirm_label.setGeometry(QtCore.QRect(30, 30, 430, 20))
        self.confirm_label.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setObjectName("confirm_label")
        self.pass_input = QtWidgets.QLineEdit(ConfirmPasswordWindow)
        self.pass_input.setGeometry(QtCore.QRect(70, 80, 350, 40))
        self.pass_input.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-radius: 15px;")
        self.pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_input.setObjectName("pass_input")
        self.confirm_button = QtWidgets.QPushButton(ConfirmPasswordWindow)
        self.confirm_button.setGeometry(QtCore.QRect(150, 200, 190, 40))
        self.confirm_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.confirm_button.setObjectName("confirm_button")

        self.retranslateUi(ConfirmPasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmPasswordWindow)

    def retranslateUi(self, ConfirmPasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmPasswordWindow.setWindowTitle(_translate("ConfirmPasswordWindow", "BudgetKeeper"))
        self.confirm_label.setText(_translate("ConfirmPasswordWindow", "Введи свой пароль для подтверждения"))
        self.pass_input.setPlaceholderText(_translate("ConfirmPasswordWindow", " пароль"))
        self.confirm_button.setText(_translate("ConfirmPasswordWindow", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmPasswordWindow = QtWidgets.QDialog()
    ui = Ui_ConfirmPasswordWindow()
    ui.setupUi(ConfirmPasswordWindow)
    ConfirmPasswordWindow.show()
    sys.exit(app.exec_())
