# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_page_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmPageWindow(object):
    def setupUi(self, ConfirmPageWindow):
        ConfirmPageWindow.setObjectName("ConfirmPageWindow")
        ConfirmPageWindow.resize(500, 170)
        ConfirmPageWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.confirm_label = QtWidgets.QLabel(ConfirmPageWindow)
        self.confirm_label.setGeometry(QtCore.QRect(120, 30, 260, 20))
        self.confirm_label.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setObjectName("confirm_label")
        self.yes_button = QtWidgets.QPushButton(ConfirmPageWindow)
        self.yes_button.setGeometry(QtCore.QRect(135, 80, 100, 40))
        self.yes_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.yes_button.setObjectName("yes_button")
        self.no_button = QtWidgets.QPushButton(ConfirmPageWindow)
        self.no_button.setGeometry(QtCore.QRect(265, 80, 100, 40))
        self.no_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.no_button.setObjectName("no_button")

        self.retranslateUi(ConfirmPageWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmPageWindow)

    def retranslateUi(self, ConfirmPageWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmPageWindow.setWindowTitle(_translate("ConfirmPageWindow", "BudgetKeeper"))
        self.confirm_label.setText(_translate("ConfirmPageWindow", "Ты точно хочешь выйти?"))
        self.yes_button.setText(_translate("ConfirmPageWindow", "Да"))
        self.no_button.setText(_translate("ConfirmPageWindow", "Нет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConfirmPageWindow = QtWidgets.QWidget()
    ui = Ui_ConfirmPageWindow()
    ui.setupUi(ConfirmPageWindow)
    ConfirmPageWindow.show()
    sys.exit(app.exec_())
