# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenuWindow(object):
    def setupUi(self, MainMenuWindow):
        MainMenuWindow.setObjectName("MainMenuWindow")
        MainMenuWindow.resize(1100, 900)
        font = QtGui.QFont()
        font.setFamily("Garamond")
        font.setPointSize(18)
        MainMenuWindow.setFont(font)
        MainMenuWindow.setMouseTracking(False)
        MainMenuWindow.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.main_widget = QtWidgets.QWidget(MainMenuWindow)
        font = QtGui.QFont()
        font.setFamily("Caviar Dreams")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.main_widget.setFont(font)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.stacked_widget = QtWidgets.QStackedWidget(self.main_widget)
        self.stacked_widget.setGeometry(QtCore.QRect(0, 0, 1100, 900))
        self.stacked_widget.setObjectName("stacked_widget")
        self.main_menu = QtWidgets.QWidget()
        self.main_menu.setObjectName("main_menu")
        self.enter_button = QtWidgets.QPushButton(self.main_menu)
        self.enter_button.setGeometry(QtCore.QRect(325, 445, 450, 60))
        font = QtGui.QFont()
        font.setFamily("Involve")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.enter_button.setFont(font)
        self.enter_button.setStyleSheet("font: 18pt \"Involve\";\n"
"background-color: rgb(242, 233, 228);\n"
"color: rgb(34, 34, 59);\n"
"border-radius: 15px;\n"
"border: 1px solid #6d6875;")
        self.enter_button.setCheckable(False)
        self.enter_button.setAutoDefault(False)
        self.enter_button.setFlat(False)
        self.enter_button.setObjectName("enter_button")
        self.reg_button = QtWidgets.QPushButton(self.main_menu)
        self.reg_button.setGeometry(QtCore.QRect(325, 525, 450, 60))
        self.reg_button.setStyleSheet("font: 18pt \"Involve\";\n"
"background-color: rgb(242, 233, 228);\n"
"color: rgb(34, 34, 59);\n"
"border-radius: 15px;\n"
"border: 1px solid #6d6875;")
        self.reg_button.setObjectName("reg_button")
        self.reg_icon = QtWidgets.QLabel(self.main_menu)
        self.reg_icon.setGeometry(QtCore.QRect(329, 532, 50, 46))
        self.reg_icon.setStyleSheet("background-color: rgb(242, 233, 228);")
        self.reg_icon.setObjectName("reg_icon")
        self.login_icon = QtWidgets.QLabel(self.main_menu)
        self.login_icon.setGeometry(QtCore.QRect(329, 452, 50, 46))
        self.login_icon.setStyleSheet("background-color: rgb(242, 233, 228);")
        self.login_icon.setObjectName("login_icon")
        self.logo = QtWidgets.QLabel(self.main_menu)
        self.logo.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo.setObjectName("logo")
        self.logo_icon = QtWidgets.QLabel(self.main_menu)
        self.logo_icon.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon.setObjectName("logo_icon")
        self.word_3 = QtWidgets.QLabel(self.main_menu)
        self.word_3.setGeometry(QtCore.QRect(330, 120, 260, 50))
        self.word_3.setStyleSheet("font: 34pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.word_3.setObjectName("word_3")
        self.word_1 = QtWidgets.QLabel(self.main_menu)
        self.word_1.setGeometry(QtCore.QRect(40, 120, 115, 50))
        self.word_1.setStyleSheet("font: 34pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.word_1.setObjectName("word_1")
        self.welcome_word = QtWidgets.QLabel(self.main_menu)
        self.welcome_word.setGeometry(QtCore.QRect(0, 370, 1100, 40))
        self.welcome_word.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.welcome_word.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_word.setObjectName("welcome_word")
        self.word_2 = QtWidgets.QLabel(self.main_menu)
        self.word_2.setGeometry(QtCore.QRect(155, 120, 175, 50))
        self.word_2.setStyleSheet("font: 63 34pt \"Involve SemiBold\";\n"
"color: rgb(229, 152, 155);")
        self.word_2.setObjectName("word_2")
        self.word_4 = QtWidgets.QLabel(self.main_menu)
        self.word_4.setGeometry(QtCore.QRect(40, 170, 651, 50))
        self.word_4.setStyleSheet("font: 34pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.word_4.setObjectName("word_4")
        self.stacked_widget.addWidget(self.main_menu)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.logo_icon_2 = QtWidgets.QLabel(self.login_page)
        self.logo_icon_2.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon_2.setObjectName("logo_icon_2")
        self.widget = QtWidgets.QWidget(self.login_page)
        self.widget.setGeometry(QtCore.QRect(300, 210, 500, 480))
        self.widget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget.setObjectName("widget")
        self.welcome_word_2 = QtWidgets.QLabel(self.widget)
        self.welcome_word_2.setGeometry(QtCore.QRect(120, 20, 260, 40))
        self.welcome_word_2.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.welcome_word_2.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_word_2.setObjectName("welcome_word_2")
        self.login_input = QtWidgets.QLineEdit(self.widget)
        self.login_input.setGeometry(QtCore.QRect(95, 130, 360, 40))
        self.login_input.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.login_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_input.setObjectName("login_input")
        self.password_input = QtWidgets.QLineEdit(self.widget)
        self.password_input.setGeometry(QtCore.QRect(95, 190, 360, 40))
        self.password_input.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setGeometry(QtCore.QRect(105, 250, 290, 50))
        self.error_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.user_icon = QtWidgets.QLabel(self.widget)
        self.user_icon.setGeometry(QtCore.QRect(45, 130, 40, 40))
        self.user_icon.setObjectName("user_icon")
        self.pass_icon = QtWidgets.QLabel(self.widget)
        self.pass_icon.setGeometry(QtCore.QRect(45, 190, 40, 40))
        self.pass_icon.setObjectName("pass_icon")
        self.login_button = QtWidgets.QPushButton(self.widget)
        self.login_button.setGeometry(QtCore.QRect(180, 350, 140, 40))
        self.login_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.login_button.setObjectName("login_button")
        self.back_button = QtWidgets.QPushButton(self.widget)
        self.back_button.setGeometry(QtCore.QRect(180, 400, 140, 40))
        self.back_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.back_button.setObjectName("back_button")
        self.logo_2 = QtWidgets.QLabel(self.login_page)
        self.logo_2.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo_2.setObjectName("logo_2")
        self.stacked_widget.addWidget(self.login_page)
        self.reg_page = QtWidgets.QWidget()
        self.reg_page.setObjectName("reg_page")
        self.widget_2 = QtWidgets.QWidget(self.reg_page)
        self.widget_2.setGeometry(QtCore.QRect(300, 210, 500, 480))
        self.widget_2.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.welcome_word_3 = QtWidgets.QLabel(self.widget_2)
        self.welcome_word_3.setGeometry(QtCore.QRect(120, 20, 260, 40))
        self.welcome_word_3.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.welcome_word_3.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_word_3.setObjectName("welcome_word_3")
        self.login_input_reg = QtWidgets.QLineEdit(self.widget_2)
        self.login_input_reg.setGeometry(QtCore.QRect(95, 130, 360, 40))
        self.login_input_reg.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.login_input_reg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_input_reg.setObjectName("login_input_reg")
        self.password_input_reg = QtWidgets.QLineEdit(self.widget_2)
        self.password_input_reg.setGeometry(QtCore.QRect(95, 190, 360, 40))
        self.password_input_reg.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.password_input_reg.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input_reg.setObjectName("password_input_reg")
        self.error_label_reg = QtWidgets.QLabel(self.widget_2)
        self.error_label_reg.setGeometry(QtCore.QRect(105, 250, 290, 50))
        self.error_label_reg.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);")
        self.error_label_reg.setText("")
        self.error_label_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label_reg.setWordWrap(True)
        self.error_label_reg.setObjectName("error_label_reg")
        self.user_icon_2 = QtWidgets.QLabel(self.widget_2)
        self.user_icon_2.setGeometry(QtCore.QRect(45, 130, 40, 40))
        self.user_icon_2.setObjectName("user_icon_2")
        self.pass_icon_2 = QtWidgets.QLabel(self.widget_2)
        self.pass_icon_2.setGeometry(QtCore.QRect(45, 190, 40, 40))
        self.pass_icon_2.setObjectName("pass_icon_2")
        self.regisrtation_button = QtWidgets.QPushButton(self.widget_2)
        self.regisrtation_button.setGeometry(QtCore.QRect(180, 350, 140, 40))
        self.regisrtation_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.regisrtation_button.setObjectName("regisrtation_button")
        self.back_button_reg = QtWidgets.QPushButton(self.widget_2)
        self.back_button_reg.setGeometry(QtCore.QRect(180, 400, 140, 40))
        self.back_button_reg.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.back_button_reg.setObjectName("back_button_reg")
        self.logo_icon_3 = QtWidgets.QLabel(self.reg_page)
        self.logo_icon_3.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon_3.setObjectName("logo_icon_3")
        self.logo_3 = QtWidgets.QLabel(self.reg_page)
        self.logo_3.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo_3.setObjectName("logo_3")
        self.stacked_widget.addWidget(self.reg_page)
        self.anketa_page = QtWidgets.QWidget()
        self.anketa_page.setObjectName("anketa_page")
        self.logo_4 = QtWidgets.QLabel(self.anketa_page)
        self.logo_4.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo_4.setObjectName("logo_4")
        self.widget_3 = QtWidgets.QWidget(self.anketa_page)
        self.widget_3.setGeometry(QtCore.QRect(175, 210, 750, 500))
        self.widget_3.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.anketa_word = QtWidgets.QLabel(self.widget_3)
        self.anketa_word.setGeometry(QtCore.QRect(285, 20, 180, 40))
        self.anketa_word.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.anketa_word.setAlignment(QtCore.Qt.AlignCenter)
        self.anketa_word.setObjectName("anketa_word")
        self.firstname = QtWidgets.QLineEdit(self.widget_3)
        self.firstname.setGeometry(QtCore.QRect(265, 160, 350, 40))
        self.firstname.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.firstname.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.firstname.setObjectName("firstname")
        self.surname = QtWidgets.QLineEdit(self.widget_3)
        self.surname.setGeometry(QtCore.QRect(265, 220, 350, 40))
        self.surname.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.surname.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.surname.setObjectName("surname")
        self.error_label_ank = QtWidgets.QLabel(self.widget_3)
        self.error_label_ank.setGeometry(QtCore.QRect(130, 330, 490, 50))
        self.error_label_ank.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);")
        self.error_label_ank.setText("")
        self.error_label_ank.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label_ank.setWordWrap(True)
        self.error_label_ank.setObjectName("error_label_ank")
        self.save_button = QtWidgets.QPushButton(self.widget_3)
        self.save_button.setGeometry(QtCore.QRect(305, 420, 140, 40))
        self.save_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.save_button.setObjectName("save_button")
        self.anketa_icon = QtWidgets.QLabel(self.widget_3)
        self.anketa_icon.setGeometry(QtCore.QRect(125, 160, 110, 160))
        self.anketa_icon.setObjectName("anketa_icon")
        self.info_label = QtWidgets.QLabel(self.widget_3)
        self.info_label.setGeometry(QtCore.QRect(100, 70, 550, 30))
        self.info_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.total_income = QtWidgets.QLineEdit(self.widget_3)
        self.total_income.setGeometry(QtCore.QRect(265, 280, 350, 40))
        self.total_income.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.total_income.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.total_income.setObjectName("total_income")
        self.logo_icon_4 = QtWidgets.QLabel(self.anketa_page)
        self.logo_icon_4.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon_4.setObjectName("logo_icon_4")
        self.stacked_widget.addWidget(self.anketa_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked_widget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stacked_widget.addWidget(self.page)
        MainMenuWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(MainMenuWindow)
        QtCore.QMetaObject.connectSlotsByName(MainMenuWindow)

    def retranslateUi(self, MainMenuWindow):
        _translate = QtCore.QCoreApplication.translate
        MainMenuWindow.setWindowTitle(_translate("MainMenuWindow", "MainWindow"))
        self.enter_button.setText(_translate("MainMenuWindow", "Войти"))
        self.reg_button.setText(_translate("MainMenuWindow", "Зарегистрироваться"))
        self.reg_icon.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/reg_icon.png\"/></p></body></html>"))
        self.login_icon.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/login_icon.png\"/></p></body></html>"))
        self.logo.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.logo_icon.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
        self.word_3.setText(_translate("MainMenuWindow", "решение "))
        self.word_1.setText(_translate("MainMenuWindow", "Твоё "))
        self.welcome_word.setText(_translate("MainMenuWindow", "Войди в свой профиль или зарегистрируйся"))
        self.word_2.setText(_translate("MainMenuWindow", "личное "))
        self.word_4.setText(_translate("MainMenuWindow", "для управления финансами"))
        self.logo_icon_2.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
        self.welcome_word_2.setText(_translate("MainMenuWindow", "Вход в профиль"))
        self.login_input.setPlaceholderText(_translate("MainMenuWindow", " логин"))
        self.password_input.setPlaceholderText(_translate("MainMenuWindow", " пароль"))
        self.user_icon.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/user_icon.png\"/></p></body></html>"))
        self.pass_icon.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/pass_icon.png\"/></p></body></html>"))
        self.login_button.setText(_translate("MainMenuWindow", "Войти"))
        self.back_button.setText(_translate("MainMenuWindow", "Назад"))
        self.logo_2.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.welcome_word_3.setText(_translate("MainMenuWindow", "Регистрация"))
        self.login_input_reg.setPlaceholderText(_translate("MainMenuWindow", " логин"))
        self.password_input_reg.setPlaceholderText(_translate("MainMenuWindow", " пароль"))
        self.user_icon_2.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/user_icon.png\"/></p></body></html>"))
        self.pass_icon_2.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/pass_icon.png\"/></p></body></html>"))
        self.regisrtation_button.setText(_translate("MainMenuWindow", "Сохранить"))
        self.back_button_reg.setText(_translate("MainMenuWindow", "Назад"))
        self.logo_icon_3.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
        self.logo_3.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.logo_4.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.anketa_word.setText(_translate("MainMenuWindow", "Анкета"))
        self.firstname.setPlaceholderText(_translate("MainMenuWindow", " имя"))
        self.surname.setPlaceholderText(_translate("MainMenuWindow", " фамилия"))
        self.save_button.setText(_translate("MainMenuWindow", "Сохранить"))
        self.anketa_icon.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/anketa_icon.png\"/></p></body></html>"))
        self.info_label.setText(_translate("MainMenuWindow", "Твои данные помогут нам настроить приложение именно под тебя"))
        self.total_income.setPlaceholderText(_translate("MainMenuWindow", " текущий доход"))
        self.logo_icon_4.setText(_translate("MainMenuWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenuWindow = QtWidgets.QMainWindow()
    ui = Ui_MainMenuWindow()
    ui.setupUi(MainMenuWindow)
    MainMenuWindow.show()
    sys.exit(app.exec_())
