# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPageWindow(object):
    def setupUi(self, MainPageWindow):
        MainPageWindow.setObjectName("MainPageWindow")
        MainPageWindow.resize(1300, 900)
        MainPageWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(MainPageWindow)
        self.widget.setGeometry(QtCore.QRect(0, 0, 250, 900))
        self.widget.setStyleSheet("background-color: rgb(255, 227, 207);")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(100, 20, 50, 50))
        self.logo.setObjectName("logo")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(40, 70, 170, 80))
        self.app_name.setObjectName("app_name")
        self.main_page_icon = QtWidgets.QLabel(self.widget)
        self.main_page_icon.setGeometry(QtCore.QRect(20, 190, 30, 30))
        self.main_page_icon.setStyleSheet("")
        self.main_page_icon.setObjectName("main_page_icon")
        self.main_page_button = QtWidgets.QPushButton(self.widget)
        self.main_page_button.setGeometry(QtCore.QRect(60, 190, 175, 30))
        self.main_page_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.main_page_button.setAutoRepeat(False)
        self.main_page_button.setObjectName("main_page_button")
        self.my_profile_icon = QtWidgets.QLabel(self.widget)
        self.my_profile_icon.setGeometry(QtCore.QRect(20, 240, 30, 30))
        self.my_profile_icon.setStyleSheet("")
        self.my_profile_icon.setObjectName("my_profile_icon")
        self.my_profile_button = QtWidgets.QPushButton(self.widget)
        self.my_profile_button.setGeometry(QtCore.QRect(60, 240, 130, 30))
        self.my_profile_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_profile_button.setAutoRepeat(False)
        self.my_profile_button.setObjectName("my_profile_button")
        self.exit_icon = QtWidgets.QLabel(self.widget)
        self.exit_icon.setGeometry(QtCore.QRect(20, 850, 30, 30))
        self.exit_icon.setObjectName("exit_icon")
        self.exit_button = QtWidgets.QPushButton(self.widget)
        self.exit_button.setGeometry(QtCore.QRect(60, 850, 60, 30))
        self.exit_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.exit_button.setObjectName("exit_button")
        self.my_accounts_icon = QtWidgets.QLabel(self.widget)
        self.my_accounts_icon.setGeometry(QtCore.QRect(20, 290, 30, 30))
        self.my_accounts_icon.setStyleSheet("")
        self.my_accounts_icon.setObjectName("my_accounts_icon")
        self.my_accounts_button = QtWidgets.QPushButton(self.widget)
        self.my_accounts_button.setGeometry(QtCore.QRect(60, 290, 100, 30))
        self.my_accounts_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_accounts_button.setAutoRepeat(False)
        self.my_accounts_button.setObjectName("my_accounts_button")
        self.transactions_icon = QtWidgets.QLabel(self.widget)
        self.transactions_icon.setGeometry(QtCore.QRect(20, 340, 30, 30))
        self.transactions_icon.setStyleSheet("")
        self.transactions_icon.setObjectName("transactions_icon")
        self.my_writings_button = QtWidgets.QPushButton(self.widget)
        self.my_writings_button.setGeometry(QtCore.QRect(60, 340, 150, 30))
        self.my_writings_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_writings_button.setAutoRepeat(False)
        self.my_writings_button.setObjectName("my_writings_button")
        self.help_icon = QtWidgets.QLabel(self.widget)
        self.help_icon.setGeometry(QtCore.QRect(20, 390, 30, 30))
        self.help_icon.setStyleSheet("")
        self.help_icon.setObjectName("help_icon")
        self.help_button = QtWidgets.QPushButton(self.widget)
        self.help_button.setGeometry(QtCore.QRect(60, 390, 80, 30))
        self.help_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.help_button.setAutoRepeat(False)
        self.help_button.setObjectName("help_button")
        self.welcome_label = QtWidgets.QLabel(MainPageWindow)
        self.welcome_label.setGeometry(QtCore.QRect(280, 0, 730, 90))
        self.welcome_label.setStyleSheet("font: 20pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.welcome_label.setText("")
        self.welcome_label.setObjectName("welcome_label")
        self.widget_2 = QtWidgets.QWidget(MainPageWindow)
        self.widget_2.setGeometry(QtCore.QRect(250, 90, 1050, 810))
        self.widget_2.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.widget_2.setObjectName("widget_2")
        self.total_income_4 = QtWidgets.QLabel(self.widget_2)
        self.total_income_4.setGeometry(QtCore.QRect(795, 60, 225, 90))
        self.total_income_4.setStyleSheet("background-color: rgb(109, 104, 117);\n"
"border-radius: 15px;\n"
"color: rgb(242, 233, 228);\n"
"font: 26pt \"Involve\";")
        self.total_income_4.setText("")
        self.total_income_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_income_4.setObjectName("total_income_4")
        self.total_income_2 = QtWidgets.QWidget(self.widget_2)
        self.total_income_2.setGeometry(QtCore.QRect(30, 240, 990, 540))
        self.total_income_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: rgb(34, 34, 59);\n"
"font: 10pt \"Involve\";")
        self.total_income_2.setObjectName("total_income_2")
        self.error_label = QtWidgets.QLabel(self.widget_2)
        self.error_label.setGeometry(QtCore.QRect(30, 180, 990, 120))
        self.error_label.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 16pt \"Involve\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.error_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.error_label.setObjectName("error_label")
        self.total_income_6 = QtWidgets.QLabel(self.widget_2)
        self.total_income_6.setGeometry(QtCore.QRect(795, 30, 225, 55))
        self.total_income_6.setStyleSheet("background-color: rgb(109, 104, 117);\n"
"border-radius: 15px;\n"
"color: rgb(34, 34, 59);\n"
"font: 63 12pt \"Involve SemiBold\";\n"
"")
        self.total_income_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.total_income_6.setObjectName("total_income_6")
        self.total_income_7 = QtWidgets.QLabel(self.widget_2)
        self.total_income_7.setGeometry(QtCore.QRect(540, 30, 225, 55))
        self.total_income_7.setStyleSheet("background-color: rgb(181, 131, 141);\n"
"border-radius: 15px;\n"
"color: rgb(34, 34, 59);\n"
"font: 63 12pt \"Involve SemiBold\";\n"
"")
        self.total_income_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.total_income_7.setObjectName("total_income_7")
        self.total_income_5 = QtWidgets.QLabel(self.widget_2)
        self.total_income_5.setGeometry(QtCore.QRect(540, 60, 225, 90))
        self.total_income_5.setStyleSheet("background-color: rgb(181, 131, 141);\n"
"border-radius: 15px;\n"
"color: rgb(242, 233, 228);\n"
"font: 26pt \"Involve\";")
        self.total_income_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.total_income_5.setObjectName("total_income_5")
        self.total_income_4.raise_()
        self.total_income_2.raise_()
        self.error_label.raise_()
        self.total_income_6.raise_()
        self.total_income_5.raise_()
        self.total_income_7.raise_()
        self.new_month_button = QtWidgets.QPushButton(MainPageWindow)
        self.new_month_button.setGeometry(QtCore.QRect(1049, 25, 221, 40))
        self.new_month_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.new_month_button.setObjectName("new_month_button")

        self.retranslateUi(MainPageWindow)
        QtCore.QMetaObject.connectSlotsByName(MainPageWindow)

    def retranslateUi(self, MainPageWindow):
        _translate = QtCore.QCoreApplication.translate
        MainPageWindow.setWindowTitle(_translate("MainPageWindow", "BudgetKeeper"))
        self.logo.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50_v2.png\"/></p></body></html>"))
        self.app_name.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/logo/logo_icon_2string_170x80_v2.png\"/></p></body></html>"))
        self.main_page_icon.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/main_page_icon_30x30.png\"/></p></body></html>"))
        self.main_page_button.setText(_translate("MainPageWindow", "Главная страница"))
        self.my_profile_icon.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/user_icon_30x30.png\"/></p></body></html>"))
        self.my_profile_button.setText(_translate("MainPageWindow", "Мой профиль"))
        self.exit_icon.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/exit_icon_30x30.png\"/></p></body></html>"))
        self.exit_button.setText(_translate("MainPageWindow", "Выход"))
        self.my_accounts_icon.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/accounts_icon_30x30.png\"/></p></body></html>"))
        self.my_accounts_button.setText(_translate("MainPageWindow", "Мои счета"))
        self.transactions_icon.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/transactions_icon_30x30.png\"/></p></body></html>"))
        self.my_writings_button.setText(_translate("MainPageWindow", "История счетов"))
        self.help_icon.setText(_translate("MainPageWindow", "<html><head/><body><p><img src=\":/icons/help_icon_30x30.png\"/></p></body></html>"))
        self.help_button.setText(_translate("MainPageWindow", "Помощь"))
        self.error_label.setText(_translate("MainPageWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.total_income_6.setText(_translate("MainPageWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#f2e9e4;\">Текущий доход</span><span style=\" color:#6d6875;\">го</span></p></body></html>"))
        self.total_income_7.setText(_translate("MainPageWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:11pt; color:#f2e9e4;\">Сумма на счетах</span><span style=\" font-size:11pt; color:#b5838d;\">го</span></p></body></html>"))
        self.total_income_5.setText(_translate("MainPageWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.new_month_button.setText(_translate("MainPageWindow", "Записать месяц"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPageWindow = QtWidgets.QWidget()
    ui = Ui_MainPageWindow()
    ui.setupUi(MainPageWindow)
    MainPageWindow.show()
    sys.exit(app.exec_())
