# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_accounts_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyAccountsPage(object):
    def setupUi(self, MyAccountsPage):
        MyAccountsPage.setObjectName("MyAccountsPage")
        MyAccountsPage.resize(1300, 900)
        MyAccountsPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(MyAccountsPage)
        self.widget.setGeometry(QtCore.QRect(0, 0, 250, 900))
        self.widget.setStyleSheet("background-color: rgb(255, 227, 207);")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(100, 20, 50, 50))
        self.logo.setObjectName("logo")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(40, 70, 170, 80))
        self.app_name.setObjectName("app_name")
        self.main_page_icon = QtWidgets.QLabel(self.widget)
        self.main_page_icon.setGeometry(QtCore.QRect(20, 190, 30, 30))
        self.main_page_icon.setStyleSheet("")
        self.main_page_icon.setObjectName("main_page_icon")
        self.main_page_button = QtWidgets.QPushButton(self.widget)
        self.main_page_button.setGeometry(QtCore.QRect(60, 190, 175, 30))
        self.main_page_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.main_page_button.setAutoRepeat(False)
        self.main_page_button.setObjectName("main_page_button")
        self.my_profile_icon = QtWidgets.QLabel(self.widget)
        self.my_profile_icon.setGeometry(QtCore.QRect(20, 240, 30, 30))
        self.my_profile_icon.setStyleSheet("")
        self.my_profile_icon.setObjectName("my_profile_icon")
        self.my_profile_button = QtWidgets.QPushButton(self.widget)
        self.my_profile_button.setGeometry(QtCore.QRect(60, 240, 130, 30))
        self.my_profile_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_profile_button.setAutoRepeat(False)
        self.my_profile_button.setObjectName("my_profile_button")
        self.exit_icon = QtWidgets.QLabel(self.widget)
        self.exit_icon.setGeometry(QtCore.QRect(20, 850, 30, 30))
        self.exit_icon.setObjectName("exit_icon")
        self.exit_button = QtWidgets.QPushButton(self.widget)
        self.exit_button.setGeometry(QtCore.QRect(60, 850, 60, 30))
        self.exit_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.exit_button.setObjectName("exit_button")
        self.my_accounts_icon = QtWidgets.QLabel(self.widget)
        self.my_accounts_icon.setGeometry(QtCore.QRect(20, 290, 30, 30))
        self.my_accounts_icon.setStyleSheet("")
        self.my_accounts_icon.setObjectName("my_accounts_icon")
        self.my_accounts_button = QtWidgets.QPushButton(self.widget)
        self.my_accounts_button.setGeometry(QtCore.QRect(60, 290, 100, 30))
        self.my_accounts_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_accounts_button.setAutoRepeat(False)
        self.my_accounts_button.setObjectName("my_accounts_button")
        self.transactions_icon = QtWidgets.QLabel(self.widget)
        self.transactions_icon.setGeometry(QtCore.QRect(20, 340, 30, 30))
        self.transactions_icon.setStyleSheet("")
        self.transactions_icon.setObjectName("transactions_icon")
        self.my_writings_button = QtWidgets.QPushButton(self.widget)
        self.my_writings_button.setGeometry(QtCore.QRect(60, 340, 150, 30))
        self.my_writings_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_writings_button.setAutoRepeat(False)
        self.my_writings_button.setObjectName("my_writings_button")
        self.help_icon = QtWidgets.QLabel(self.widget)
        self.help_icon.setGeometry(QtCore.QRect(20, 390, 30, 30))
        self.help_icon.setStyleSheet("")
        self.help_icon.setObjectName("help_icon")
        self.help_button = QtWidgets.QPushButton(self.widget)
        self.help_button.setGeometry(QtCore.QRect(60, 390, 80, 30))
        self.help_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.help_button.setAutoRepeat(False)
        self.help_button.setObjectName("help_button")
        self.welcome_label = QtWidgets.QLabel(MyAccountsPage)
        self.welcome_label.setGeometry(QtCore.QRect(329, 0, 791, 90))
        self.welcome_label.setStyleSheet("font: 20pt \"Involve\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 59);")
        self.welcome_label.setObjectName("welcome_label")
        self.label_3 = QtWidgets.QLabel(MyAccountsPage)
        self.label_3.setGeometry(QtCore.QRect(290, 0, 30, 90))
        self.label_3.setObjectName("label_3")
        self.widget_2 = QtWidgets.QWidget(MyAccountsPage)
        self.widget_2.setGeometry(QtCore.QRect(250, 90, 1050, 810))
        self.widget_2.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.widget_2.setObjectName("widget_2")
        self.rename_button = QtWidgets.QPushButton(self.widget_2)
        self.rename_button.setGeometry(QtCore.QRect(800, 660, 220, 40))
        self.rename_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.rename_button.setObjectName("rename_button")
        self.add_button = QtWidgets.QPushButton(self.widget_2)
        self.add_button.setGeometry(QtCore.QRect(800, 730, 220, 40))
        self.add_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.add_button.setObjectName("add_button")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(30, 660, 740, 110))
        self.label.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 12pt \"Involve\";")
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setGeometry(QtCore.QRect(30, 110, 990, 520))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_widget = QtWidgets.QWidget()
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 990, 520))
        self.scroll_widget.setObjectName("scroll_widget")
        self.scrollArea.setWidget(self.scroll_widget)
        self.error_label = QtWidgets.QLabel(self.widget_2)
        self.error_label.setGeometry(QtCore.QRect(30, 30, 990, 101))
        self.error_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-radius: 15px;")
        self.error_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.error_label.setObjectName("error_label")

        self.retranslateUi(MyAccountsPage)
        QtCore.QMetaObject.connectSlotsByName(MyAccountsPage)

    def retranslateUi(self, MyAccountsPage):
        _translate = QtCore.QCoreApplication.translate
        MyAccountsPage.setWindowTitle(_translate("MyAccountsPage", "BudgetKeeper"))
        self.logo.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50_v2.png\"/></p></body></html>"))
        self.app_name.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/logo/logo_icon_2string_170x80_v2.png\"/></p></body></html>"))
        self.main_page_icon.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/main_page_icon_30x30.png\"/></p></body></html>"))
        self.main_page_button.setText(_translate("MyAccountsPage", "Главная страница"))
        self.my_profile_icon.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/user_icon_30x30.png\"/></p></body></html>"))
        self.my_profile_button.setText(_translate("MyAccountsPage", "Мой профиль"))
        self.exit_icon.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/exit_icon_30x30.png\"/></p></body></html>"))
        self.exit_button.setText(_translate("MyAccountsPage", "Выход"))
        self.my_accounts_icon.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/accounts_icon_30x30.png\"/></p></body></html>"))
        self.my_accounts_button.setText(_translate("MyAccountsPage", "Мои счета"))
        self.transactions_icon.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/transactions_icon_30x30.png\"/></p></body></html>"))
        self.my_writings_button.setText(_translate("MyAccountsPage", "История счетов"))
        self.help_icon.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/help_icon_30x30.png\"/></p></body></html>"))
        self.help_button.setText(_translate("MyAccountsPage", "Помощь"))
        self.welcome_label.setText(_translate("MyAccountsPage", "Мои счета"))
        self.label_3.setText(_translate("MyAccountsPage", "<html><head/><body><p><img src=\":/icons/accounts_icon_30x30.png\"/></p></body></html>"))
        self.rename_button.setText(_translate("MyAccountsPage", "Редактировать"))
        self.add_button.setText(_translate("MyAccountsPage", "Добавить счёт"))
        self.label.setText(_translate("MyAccountsPage", "<html><head/><body><p>Ты можешь <span style=\" font-weight:600; color:#e5989b;\">редактировать </span>те счета, которые уже есть у тебя</p><p>Также ты можешь <span style=\" font-weight:600; color:#e5989b;\">добавить</span> новые счета, но их количество <span style=\" color:#22223b;\">ограничено</span> - <span style=\" font-weight:600; color:#e5989b;\">10 счетов</span> всего</p><p>Чтобы <span style=\" font-weight:600; color:#e5989b;\">удалить</span> счёт, нажми на кнопку корзины рядом с ним</p></body></html>"))
        self.error_label.setText(_translate("MyAccountsPage", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">а тут что?</span></p><p>Здесь ты можешь <span style=\" font-weight:600; color:#e5989b;\">изменить</span> или <span style=\" font-weight:600; color:#e5989b;\">удалить</span> свои счета</p></body></html>"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyAccountsPage = QtWidgets.QWidget()
    ui = Ui_MyAccountsPage()
    ui.setupUi(MyAccountsPage)
    MyAccountsPage.show()
    sys.exit(app.exec_())
