# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_accounts_history_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyAccountsHistoryPage(object):
    def setupUi(self, MyAccountsHistoryPage):
        MyAccountsHistoryPage.setObjectName("MyAccountsHistoryPage")
        MyAccountsHistoryPage.resize(1600, 980)
        MyAccountsHistoryPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(MyAccountsHistoryPage)
        self.widget.setGeometry(QtCore.QRect(0, 0, 250, 980))
        self.widget.setStyleSheet("background-color: rgb(255, 227, 207);")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(100, 20, 50, 50))
        self.logo.setObjectName("logo")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(40, 70, 170, 80))
        self.app_name.setObjectName("app_name")
        self.main_page_icon = QtWidgets.QLabel(self.widget)
        self.main_page_icon.setGeometry(QtCore.QRect(20, 190, 30, 30))
        self.main_page_icon.setStyleSheet("")
        self.main_page_icon.setObjectName("main_page_icon")
        self.main_page_button = QtWidgets.QPushButton(self.widget)
        self.main_page_button.setGeometry(QtCore.QRect(60, 190, 175, 30))
        self.main_page_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.main_page_button.setAutoRepeat(False)
        self.main_page_button.setObjectName("main_page_button")
        self.my_profile_icon = QtWidgets.QLabel(self.widget)
        self.my_profile_icon.setGeometry(QtCore.QRect(20, 240, 30, 30))
        self.my_profile_icon.setStyleSheet("")
        self.my_profile_icon.setObjectName("my_profile_icon")
        self.my_profile_button = QtWidgets.QPushButton(self.widget)
        self.my_profile_button.setGeometry(QtCore.QRect(60, 240, 130, 30))
        self.my_profile_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_profile_button.setAutoRepeat(False)
        self.my_profile_button.setObjectName("my_profile_button")
        self.exit_icon = QtWidgets.QLabel(self.widget)
        self.exit_icon.setGeometry(QtCore.QRect(20, 930, 30, 30))
        self.exit_icon.setObjectName("exit_icon")
        self.exit_button = QtWidgets.QPushButton(self.widget)
        self.exit_button.setGeometry(QtCore.QRect(60, 930, 60, 30))
        self.exit_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.exit_button.setObjectName("exit_button")
        self.my_accounts_icon = QtWidgets.QLabel(self.widget)
        self.my_accounts_icon.setGeometry(QtCore.QRect(20, 290, 30, 30))
        self.my_accounts_icon.setStyleSheet("")
        self.my_accounts_icon.setObjectName("my_accounts_icon")
        self.my_accounts_button = QtWidgets.QPushButton(self.widget)
        self.my_accounts_button.setGeometry(QtCore.QRect(60, 290, 100, 30))
        self.my_accounts_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_accounts_button.setAutoRepeat(False)
        self.my_accounts_button.setObjectName("my_accounts_button")
        self.transactions_icon = QtWidgets.QLabel(self.widget)
        self.transactions_icon.setGeometry(QtCore.QRect(20, 340, 30, 30))
        self.transactions_icon.setStyleSheet("")
        self.transactions_icon.setObjectName("transactions_icon")
        self.my_writings_button = QtWidgets.QPushButton(self.widget)
        self.my_writings_button.setGeometry(QtCore.QRect(60, 340, 150, 30))
        self.my_writings_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_writings_button.setAutoRepeat(False)
        self.my_writings_button.setObjectName("my_writings_button")
        self.help_icon = QtWidgets.QLabel(self.widget)
        self.help_icon.setGeometry(QtCore.QRect(20, 390, 30, 30))
        self.help_icon.setStyleSheet("")
        self.help_icon.setObjectName("help_icon")
        self.help_button = QtWidgets.QPushButton(self.widget)
        self.help_button.setGeometry(QtCore.QRect(60, 390, 80, 30))
        self.help_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.help_button.setAutoRepeat(False)
        self.help_button.setObjectName("help_button")
        self.label_3 = QtWidgets.QLabel(MyAccountsHistoryPage)
        self.label_3.setGeometry(QtCore.QRect(290, 0, 30, 90))
        self.label_3.setObjectName("label_3")
        self.welcome_label = QtWidgets.QLabel(MyAccountsHistoryPage)
        self.welcome_label.setGeometry(QtCore.QRect(330, 0, 321, 90))
        self.welcome_label.setStyleSheet("font: 20pt \"Involve\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 59);")
        self.welcome_label.setObjectName("welcome_label")
        self.widget_2 = QtWidgets.QWidget(MyAccountsHistoryPage)
        self.widget_2.setGeometry(QtCore.QRect(250, 90, 1350, 890))
        self.widget_2.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.widget_2.setObjectName("widget_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea.setGeometry(QtCore.QRect(30, 30, 1290, 750))
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget_for_tables = QtWidgets.QWidget()
        self.widget_for_tables.setGeometry(QtCore.QRect(0, 0, 1290, 750))
        self.widget_for_tables.setFocusPolicy(QtCore.Qt.NoFocus)
        self.widget_for_tables.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"font: 11pt \"Involve\";")
        self.widget_for_tables.setObjectName("widget_for_tables")
        self.scrollArea.setWidget(self.widget_for_tables)
        self.error_label = QtWidgets.QLabel(self.widget_2)
        self.error_label.setGeometry(QtCore.QRect(30, 810, 1290, 50))
        self.error_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.set_period_button = QtWidgets.QPushButton(MyAccountsHistoryPage)
        self.set_period_button.setGeometry(QtCore.QRect(1420, 30, 150, 40))
        self.set_period_button.setStyleSheet("border-radius: 15px;\n"
"font: 12pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.set_period_button.setObjectName("set_period_button")
        self.comboBox_month_end = QtWidgets.QComboBox(MyAccountsHistoryPage)
        self.comboBox_month_end.setGeometry(QtCore.QRect(1200, 40, 100, 20))
        self.comboBox_month_end.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Involve\";\n"
"")
        self.comboBox_month_end.setEditable(True)
        self.comboBox_month_end.setObjectName("comboBox_month_end")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.comboBox_month_end.addItem("")
        self.label_7 = QtWidgets.QLabel(MyAccountsHistoryPage)
        self.label_7.setGeometry(QtCore.QRect(1175, 50, 15, 3))
        self.label_7.setStyleSheet("background-color: rgb(34, 34, 59);\n"
"border-radius: 15px;\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.comboBox_year_end = QtWidgets.QComboBox(MyAccountsHistoryPage)
        self.comboBox_year_end.setGeometry(QtCore.QRect(1315, 40, 70, 20))
        self.comboBox_year_end.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Involve\";")
        self.comboBox_year_end.setEditable(True)
        self.comboBox_year_end.setCurrentText("")
        self.comboBox_year_end.setObjectName("comboBox_year_end")
        self.label = QtWidgets.QLabel(MyAccountsHistoryPage)
        self.label.setGeometry(QtCore.QRect(650, 30, 740, 40))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-radius: 15px;\n"
"border-color: rgb(109, 104, 117);")
        self.label.setObjectName("label")
        self.comboBox_month_start = QtWidgets.QComboBox(MyAccountsHistoryPage)
        self.comboBox_month_start.setGeometry(QtCore.QRect(975, 40, 100, 20))
        self.comboBox_month_start.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Involve\";\n"
"")
        self.comboBox_month_start.setEditable(True)
        self.comboBox_month_start.setObjectName("comboBox_month_start")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_month_start.addItem("")
        self.comboBox_year_start = QtWidgets.QComboBox(MyAccountsHistoryPage)
        self.comboBox_year_start.setGeometry(QtCore.QRect(1090, 40, 70, 20))
        self.comboBox_year_start.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Involve\";")
        self.comboBox_year_start.setEditable(True)
        self.comboBox_year_start.setObjectName("comboBox_year_start")
        self.label.raise_()
        self.widget.raise_()
        self.label_3.raise_()
        self.welcome_label.raise_()
        self.widget_2.raise_()
        self.set_period_button.raise_()
        self.comboBox_month_end.raise_()
        self.label_7.raise_()
        self.comboBox_year_end.raise_()
        self.comboBox_month_start.raise_()
        self.comboBox_year_start.raise_()

        self.retranslateUi(MyAccountsHistoryPage)
        QtCore.QMetaObject.connectSlotsByName(MyAccountsHistoryPage)

    def retranslateUi(self, MyAccountsHistoryPage):
        _translate = QtCore.QCoreApplication.translate
        MyAccountsHistoryPage.setWindowTitle(_translate("MyAccountsHistoryPage", "BudgetKeeper"))
        self.logo.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50_v2.png\"/></p></body></html>"))
        self.app_name.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/logo/logo_icon_2string_170x80_v2.png\"/></p></body></html>"))
        self.main_page_icon.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/main_page_icon_30x30.png\"/></p></body></html>"))
        self.main_page_button.setText(_translate("MyAccountsHistoryPage", "Главная страница"))
        self.my_profile_icon.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/user_icon_30x30.png\"/></p></body></html>"))
        self.my_profile_button.setText(_translate("MyAccountsHistoryPage", "Мой профиль"))
        self.exit_icon.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/exit_icon_30x30.png\"/></p></body></html>"))
        self.exit_button.setText(_translate("MyAccountsHistoryPage", "Выход"))
        self.my_accounts_icon.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/accounts_icon_30x30.png\"/></p></body></html>"))
        self.my_accounts_button.setText(_translate("MyAccountsHistoryPage", "Мои счета"))
        self.transactions_icon.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/transactions_icon_30x30.png\"/></p></body></html>"))
        self.my_writings_button.setText(_translate("MyAccountsHistoryPage", "История счетов"))
        self.help_icon.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/help_icon_30x30.png\"/></p></body></html>"))
        self.help_button.setText(_translate("MyAccountsHistoryPage", "Помощь"))
        self.label_3.setText(_translate("MyAccountsHistoryPage", "<html><head/><body><p><img src=\":/icons/transactions_icon_30x30.png\"/></p></body></html>"))
        self.welcome_label.setText(_translate("MyAccountsHistoryPage", "История счетов"))
        self.set_period_button.setText(_translate("MyAccountsHistoryPage", "Установить"))
        self.comboBox_month_end.setItemText(0, _translate("MyAccountsHistoryPage", "Январь"))
        self.comboBox_month_end.setItemText(1, _translate("MyAccountsHistoryPage", "Февраль"))
        self.comboBox_month_end.setItemText(2, _translate("MyAccountsHistoryPage", "Март"))
        self.comboBox_month_end.setItemText(3, _translate("MyAccountsHistoryPage", "Апрель"))
        self.comboBox_month_end.setItemText(4, _translate("MyAccountsHistoryPage", "Май"))
        self.comboBox_month_end.setItemText(5, _translate("MyAccountsHistoryPage", "Июнь"))
        self.comboBox_month_end.setItemText(6, _translate("MyAccountsHistoryPage", "Июль"))
        self.comboBox_month_end.setItemText(7, _translate("MyAccountsHistoryPage", "Август"))
        self.comboBox_month_end.setItemText(8, _translate("MyAccountsHistoryPage", "Сентябрь"))
        self.comboBox_month_end.setItemText(9, _translate("MyAccountsHistoryPage", "Октябрь"))
        self.comboBox_month_end.setItemText(10, _translate("MyAccountsHistoryPage", "Ноябрь"))
        self.comboBox_month_end.setItemText(11, _translate("MyAccountsHistoryPage", "Декабрь"))
        self.label.setText(_translate("MyAccountsHistoryPage", "   Период для отображения истории:"))
        self.comboBox_month_start.setItemText(0, _translate("MyAccountsHistoryPage", "Январь"))
        self.comboBox_month_start.setItemText(1, _translate("MyAccountsHistoryPage", "Февраль"))
        self.comboBox_month_start.setItemText(2, _translate("MyAccountsHistoryPage", "Март"))
        self.comboBox_month_start.setItemText(3, _translate("MyAccountsHistoryPage", "Апрель"))
        self.comboBox_month_start.setItemText(4, _translate("MyAccountsHistoryPage", "Май"))
        self.comboBox_month_start.setItemText(5, _translate("MyAccountsHistoryPage", "Июнь"))
        self.comboBox_month_start.setItemText(6, _translate("MyAccountsHistoryPage", "Июль"))
        self.comboBox_month_start.setItemText(7, _translate("MyAccountsHistoryPage", "Август"))
        self.comboBox_month_start.setItemText(8, _translate("MyAccountsHistoryPage", "Сентябрь"))
        self.comboBox_month_start.setItemText(9, _translate("MyAccountsHistoryPage", "Октябрь"))
        self.comboBox_month_start.setItemText(10, _translate("MyAccountsHistoryPage", "Ноябрь"))
        self.comboBox_month_start.setItemText(11, _translate("MyAccountsHistoryPage", "Декабрь"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyAccountsHistoryPage = QtWidgets.QWidget()
    ui = Ui_MyAccountsHistoryPage()
    ui.setupUi(MyAccountsHistoryPage)
    MyAccountsHistoryPage.show()
    sys.exit(app.exec_())
