# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_profile_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyProfilePage(object):
    def setupUi(self, MyProfilePage):
        MyProfilePage.setObjectName("MyProfilePage")
        MyProfilePage.resize(1300, 900)
        MyProfilePage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget = QtWidgets.QWidget(MyProfilePage)
        self.widget.setGeometry(QtCore.QRect(0, 0, 250, 900))
        self.widget.setStyleSheet("background-color: rgb(255, 227, 207);")
        self.widget.setObjectName("widget")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(100, 20, 50, 50))
        self.logo.setObjectName("logo")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(40, 70, 170, 80))
        self.app_name.setObjectName("app_name")
        self.main_page_icon = QtWidgets.QLabel(self.widget)
        self.main_page_icon.setGeometry(QtCore.QRect(20, 190, 30, 30))
        self.main_page_icon.setStyleSheet("")
        self.main_page_icon.setObjectName("main_page_icon")
        self.main_page_button = QtWidgets.QPushButton(self.widget)
        self.main_page_button.setGeometry(QtCore.QRect(60, 190, 175, 30))
        self.main_page_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.main_page_button.setAutoRepeat(False)
        self.main_page_button.setObjectName("main_page_button")
        self.my_profile_icon = QtWidgets.QLabel(self.widget)
        self.my_profile_icon.setGeometry(QtCore.QRect(20, 240, 30, 30))
        self.my_profile_icon.setStyleSheet("")
        self.my_profile_icon.setObjectName("my_profile_icon")
        self.my_profile_button = QtWidgets.QPushButton(self.widget)
        self.my_profile_button.setGeometry(QtCore.QRect(60, 240, 130, 30))
        self.my_profile_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_profile_button.setAutoRepeat(False)
        self.my_profile_button.setObjectName("my_profile_button")
        self.exit_icon = QtWidgets.QLabel(self.widget)
        self.exit_icon.setGeometry(QtCore.QRect(20, 850, 30, 30))
        self.exit_icon.setObjectName("exit_icon")
        self.exit_button = QtWidgets.QPushButton(self.widget)
        self.exit_button.setGeometry(QtCore.QRect(60, 850, 60, 30))
        self.exit_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.exit_button.setObjectName("exit_button")
        self.my_accounts_icon = QtWidgets.QLabel(self.widget)
        self.my_accounts_icon.setGeometry(QtCore.QRect(20, 290, 30, 30))
        self.my_accounts_icon.setStyleSheet("")
        self.my_accounts_icon.setObjectName("my_accounts_icon")
        self.my_accounts_button = QtWidgets.QPushButton(self.widget)
        self.my_accounts_button.setGeometry(QtCore.QRect(60, 290, 100, 30))
        self.my_accounts_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_accounts_button.setAutoRepeat(False)
        self.my_accounts_button.setObjectName("my_accounts_button")
        self.transactions_icon = QtWidgets.QLabel(self.widget)
        self.transactions_icon.setGeometry(QtCore.QRect(20, 340, 30, 30))
        self.transactions_icon.setStyleSheet("")
        self.transactions_icon.setObjectName("transactions_icon")
        self.my_writings_button = QtWidgets.QPushButton(self.widget)
        self.my_writings_button.setGeometry(QtCore.QRect(60, 340, 150, 30))
        self.my_writings_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.my_writings_button.setAutoRepeat(False)
        self.my_writings_button.setObjectName("my_writings_button")
        self.help_icon = QtWidgets.QLabel(self.widget)
        self.help_icon.setGeometry(QtCore.QRect(20, 390, 30, 30))
        self.help_icon.setStyleSheet("")
        self.help_icon.setObjectName("help_icon")
        self.help_button = QtWidgets.QPushButton(self.widget)
        self.help_button.setGeometry(QtCore.QRect(60, 390, 80, 30))
        self.help_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);\n"
"border-color: rgb(34, 34, 59);")
        self.help_button.setAutoRepeat(False)
        self.help_button.setObjectName("help_button")
        self.welcome_label = QtWidgets.QLabel(MyProfilePage)
        self.welcome_label.setGeometry(QtCore.QRect(329, 0, 791, 90))
        self.welcome_label.setStyleSheet("font: 20pt \"Involve\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(34, 34, 59);")
        self.welcome_label.setObjectName("welcome_label")
        self.widget_2 = QtWidgets.QWidget(MyProfilePage)
        self.widget_2.setGeometry(QtCore.QRect(250, 90, 1050, 810))
        self.widget_2.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.widget_2.setObjectName("widget_2")
        self.edit_button = QtWidgets.QPushButton(self.widget_2)
        self.edit_button.setGeometry(QtCore.QRect(800, 660, 220, 40))
        self.edit_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.edit_button.setObjectName("edit_button")
        self.save_button = QtWidgets.QPushButton(self.widget_2)
        self.save_button.setGeometry(QtCore.QRect(800, 730, 220, 40))
        self.save_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.save_button.setObjectName("save_button")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(30, 660, 740, 110))
        self.label.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 12pt \"Involve\";")
        self.label.setObjectName("label")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(30, 30, 990, 601))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.login_line = QtWidgets.QLineEdit(self.widget_3)
        self.login_line.setGeometry(QtCore.QRect(350, 130, 350, 40))
        self.login_line.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.login_line.setReadOnly(True)
        self.login_line.setObjectName("login_line")
        self.login_label = QtWidgets.QLabel(self.widget_3)
        self.login_label.setGeometry(QtCore.QRect(90, 135, 250, 30))
        self.login_label.setStyleSheet("color: rgb(229, 152, 155);\n"
"font: 63 14pt \"Involve\";")
        self.login_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.login_label.setObjectName("login_label")
        self.pass_label = QtWidgets.QLabel(self.widget_3)
        self.pass_label.setGeometry(QtCore.QRect(90, 205, 250, 30))
        self.pass_label.setStyleSheet("color: rgb(229, 152, 155);\n"
"font: 63 14pt \"Involve\";")
        self.pass_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pass_label.setObjectName("pass_label")
        self.password_line = QtWidgets.QLineEdit(self.widget_3)
        self.password_line.setGeometry(QtCore.QRect(350, 200, 350, 40))
        self.password_line.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line.setReadOnly(True)
        self.password_line.setObjectName("password_line")
        self.first_name_line = QtWidgets.QLineEdit(self.widget_3)
        self.first_name_line.setGeometry(QtCore.QRect(350, 270, 350, 40))
        self.first_name_line.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.first_name_line.setReadOnly(True)
        self.first_name_line.setObjectName("first_name_line")
        self.firstname_label = QtWidgets.QLabel(self.widget_3)
        self.firstname_label.setGeometry(QtCore.QRect(90, 275, 250, 30))
        self.firstname_label.setStyleSheet("color: rgb(229, 152, 155);\n"
"font: 63 14pt \"Involve\";")
        self.firstname_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.firstname_label.setObjectName("firstname_label")
        self.sur_name_line = QtWidgets.QLineEdit(self.widget_3)
        self.sur_name_line.setGeometry(QtCore.QRect(350, 340, 350, 40))
        self.sur_name_line.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.sur_name_line.setReadOnly(True)
        self.sur_name_line.setObjectName("sur_name_line")
        self.sur_name_label = QtWidgets.QLabel(self.widget_3)
        self.sur_name_label.setGeometry(QtCore.QRect(90, 345, 250, 30))
        self.sur_name_label.setStyleSheet("color: rgb(229, 152, 155);\n"
"font: 63 14pt \"Involve\";")
        self.sur_name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sur_name_label.setObjectName("sur_name_label")
        self.income_line = QtWidgets.QLineEdit(self.widget_3)
        self.income_line.setGeometry(QtCore.QRect(350, 410, 350, 40))
        self.income_line.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.income_line.setReadOnly(True)
        self.income_line.setObjectName("income_line")
        self.sur_name_label_2 = QtWidgets.QLabel(self.widget_3)
        self.sur_name_label_2.setGeometry(QtCore.QRect(90, 415, 250, 30))
        self.sur_name_label_2.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 63 14pt \"Involve\";")
        self.sur_name_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sur_name_label_2.setObjectName("sur_name_label_2")
        self.show_pass_button = QtWidgets.QPushButton(self.widget_3)
        self.show_pass_button.setGeometry(QtCore.QRect(710, 200, 40, 40))
        self.show_pass_button.setStyleSheet("background-image: url(:/icons/show_pass_icon_40x40.png);")
        self.show_pass_button.setText("")
        self.show_pass_button.setObjectName("show_pass_button")
        self.welcome_label_2 = QtWidgets.QLabel(self.widget_3)
        self.welcome_label_2.setGeometry(QtCore.QRect(0, 30, 990, 40))
        self.welcome_label_2.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.welcome_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label_2.setObjectName("welcome_label_2")
        self.error_label = QtWidgets.QLabel(self.widget_3)
        self.error_label.setGeometry(QtCore.QRect(220, 520, 550, 50))
        self.error_label.setStyleSheet("color: rgb(181, 131, 141);\n"
"font: 12pt \"Involve\";")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.login_line.raise_()
        self.login_label.raise_()
        self.pass_label.raise_()
        self.password_line.raise_()
        self.first_name_line.raise_()
        self.firstname_label.raise_()
        self.sur_name_line.raise_()
        self.sur_name_label.raise_()
        self.income_line.raise_()
        self.sur_name_label_2.raise_()
        self.welcome_label_2.raise_()
        self.error_label.raise_()
        self.show_pass_button.raise_()
        self.label_3 = QtWidgets.QLabel(MyProfilePage)
        self.label_3.setGeometry(QtCore.QRect(290, 0, 30, 90))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(MyProfilePage)
        QtCore.QMetaObject.connectSlotsByName(MyProfilePage)

    def retranslateUi(self, MyProfilePage):
        _translate = QtCore.QCoreApplication.translate
        MyProfilePage.setWindowTitle(_translate("MyProfilePage", "BudgetKeeper"))
        self.logo.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50_v2.png\"/></p></body></html>"))
        self.app_name.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/logo/logo_icon_2string_170x80_v2.png\"/></p></body></html>"))
        self.main_page_icon.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/main_page_icon_30x30.png\"/></p></body></html>"))
        self.main_page_button.setText(_translate("MyProfilePage", "Главная страница"))
        self.my_profile_icon.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/user_icon_30x30.png\"/></p></body></html>"))
        self.my_profile_button.setText(_translate("MyProfilePage", "Мой профиль"))
        self.exit_icon.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/exit_icon_30x30.png\"/></p></body></html>"))
        self.exit_button.setText(_translate("MyProfilePage", "Выход"))
        self.my_accounts_icon.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/accounts_icon_30x30.png\"/></p></body></html>"))
        self.my_accounts_button.setText(_translate("MyProfilePage", "Мои счета"))
        self.transactions_icon.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/transactions_icon_30x30.png\"/></p></body></html>"))
        self.my_writings_button.setText(_translate("MyProfilePage", "История счетов"))
        self.help_icon.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/help_icon_30x30.png\"/></p></body></html>"))
        self.help_button.setText(_translate("MyProfilePage", "Помощь"))
        self.welcome_label.setText(_translate("MyProfilePage", "Мой профиль"))
        self.edit_button.setText(_translate("MyProfilePage", "Редактировать"))
        self.save_button.setText(_translate("MyProfilePage", "Сохранить"))
        self.label.setText(_translate("MyProfilePage", "<html><head/><body><p>При изменении данных потребуется ввести <span style=\" font-weight:600; color:#e5989b;\">пароль</span> пользователя</p><p>При <span style=\" color:#22223b;\">изменении</span> пароля, в окне-подтверждении вводи <span style=\" font-weight:600; color:#e5989b;\">старый пароль</span></p><p>Без нажатия кнопки &quot;<span style=\" font-weight:600; color:#e5989b;\">Сохранить</span>&quot; введённые тобой данные <span style=\" font-weight:600; color:#e5989b;\">не сохранятся</span></p></body></html>"))
        self.login_label.setText(_translate("MyProfilePage", "<html><head/><body><p><span style=\" font-weight:400; color:#22223b;\">Логин </span></p></body></html>"))
        self.pass_label.setText(_translate("MyProfilePage", "<html><head/><body><p><span style=\" font-weight:400; color:#22223b;\">Пароль</span></p></body></html>"))
        self.firstname_label.setText(_translate("MyProfilePage", "<html><head/><body><p><span style=\" font-weight:400; color:#22223b;\">Имя</span></p></body></html>"))
        self.sur_name_label.setText(_translate("MyProfilePage", "<html><head/><body><p><span style=\" font-weight:400; color:#22223b;\">Фамилия</span></p></body></html>"))
        self.sur_name_label_2.setText(_translate("MyProfilePage", "<html><head/><body><p><span style=\" font-weight:400;\">Доход</span></p></body></html>"))
        self.welcome_label_2.setText(_translate("MyProfilePage", "<html><head/><body><p>Здесь ты можешь <span style=\" font-weight:600; color:#e5989b;\">просмотреть</span> и <span style=\" font-weight:600; color:#e5989b;\">изменить</span> свои данные</p></body></html>"))
        self.label_3.setText(_translate("MyProfilePage", "<html><head/><body><p><img src=\":/icons/user_icon_30x30.png\"/></p></body></html>"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyProfilePage = QtWidgets.QWidget()
    ui = Ui_MyProfilePage()
    ui.setupUi(MyProfilePage)
    MyProfilePage.show()
    sys.exit(app.exec_())
