# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_accounts_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewAccountsWindow(object):
    def setupUi(self, NewAccountsWindow):
        NewAccountsWindow.setObjectName("NewAccountsWindow")
        NewAccountsWindow.resize(800, 870)
        NewAccountsWindow.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.tips_label = QtWidgets.QLabel(NewAccountsWindow)
        self.tips_label.setGeometry(QtCore.QRect(50, 800, 390, 40))
        self.tips_label.setStyleSheet("font: 10pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.tips_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tips_label.setWordWrap(True)
        self.tips_label.setObjectName("tips_label")
        self.save_button = QtWidgets.QPushButton(NewAccountsWindow)
        self.save_button.setGeometry(QtCore.QRect(620, 800, 140, 40))
        self.save_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.save_button.setObjectName("save_button")
        self.logo_icon = QtWidgets.QLabel(NewAccountsWindow)
        self.logo_icon.setGeometry(QtCore.QRect(30, 30, 50, 50))
        self.logo_icon.setObjectName("logo_icon")
        self.logo = QtWidgets.QLabel(NewAccountsWindow)
        self.logo.setGeometry(QtCore.QRect(90, 30, 240, 50))
        self.logo.setObjectName("logo")
        self.error_label = QtWidgets.QLabel(NewAccountsWindow)
        self.error_label.setGeometry(QtCore.QRect(50, 730, 700, 50))
        self.error_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.back_button = QtWidgets.QPushButton(NewAccountsWindow)
        self.back_button.setGeometry(QtCore.QRect(460, 800, 140, 40))
        self.back_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"border-color: rgb(34, 34, 59);\n"
"color: rgb(255, 180, 162);\n"
"background-color: rgb(34, 34, 59);")
        self.back_button.setObjectName("back_button")
        self.label_2 = QtWidgets.QLabel(NewAccountsWindow)
        self.label_2.setGeometry(QtCore.QRect(57, 110, 615, 30))
        self.label_2.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.spinBox = QtWidgets.QSpinBox(NewAccountsWindow)
        self.spinBox.setGeometry(QtCore.QRect(675, 110, 60, 30))
        self.spinBox.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.create_button = QtWidgets.QPushButton(NewAccountsWindow)
        self.create_button.setGeometry(QtCore.QRect(610, 160, 140, 40))
        self.create_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.create_button.setObjectName("create_button")
        self.scrollArea = QtWidgets.QScrollArea(NewAccountsWindow)
        self.scrollArea.setGeometry(QtCore.QRect(50, 220, 700, 500))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.accounts_forms = QtWidgets.QWidget()
        self.accounts_forms.setGeometry(QtCore.QRect(0, 0, 700, 500))
        self.accounts_forms.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"font: 12pt \"Involve\";")
        self.accounts_forms.setObjectName("accounts_forms")
        self.scrollArea.setWidget(self.accounts_forms)

        self.retranslateUi(NewAccountsWindow)
        QtCore.QMetaObject.connectSlotsByName(NewAccountsWindow)

    def retranslateUi(self, NewAccountsWindow):
        _translate = QtCore.QCoreApplication.translate
        NewAccountsWindow.setWindowTitle(_translate("NewAccountsWindow", "BudgetKeeper"))
        self.tips_label.setText(_translate("NewAccountsWindow", "<html><head/><body><p><span style=\" color:#22223b;\">При выходе данные не сохраняются</span></p></body></html>"))
        self.save_button.setText(_translate("NewAccountsWindow", "Сохранить"))
        self.logo_icon.setText(_translate("NewAccountsWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
        self.logo.setText(_translate("NewAccountsWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.back_button.setText(_translate("NewAccountsWindow", "Назад"))
        self.label_2.setText(_translate("NewAccountsWindow", "<html><head/><body><p><span style=\" color:#22223b;\">Выбери </span><span style=\" font-weight:600; color:#e5989b;\">количество</span> счетов, которое ты хочешь добавить:</p></body></html>"))
        self.create_button.setText(_translate("NewAccountsWindow", "Добавить"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewAccountsWindow = QtWidgets.QWidget()
    ui = Ui_NewAccountsWindow()
    ui.setupUi(NewAccountsWindow)
    NewAccountsWindow.show()
    sys.exit(app.exec_())
