# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg_page_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main_menu_logo_rc


class Ui_RegPageWindow(object):
    def setupUi(self, RegPageWindow):
        RegPageWindow.setObjectName("RegPageWindow")
        RegPageWindow.resize(1100, 900)
        RegPageWindow.setStyleSheet("background-color: rgb(238, 237, 240);")
        self.logo_icon = QtWidgets.QLabel(RegPageWindow)
        self.logo_icon.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon.setObjectName("logo_icon")
        self.logo = QtWidgets.QLabel(RegPageWindow)
        self.logo.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo.setObjectName("logo")
        self.widget = QtWidgets.QWidget(RegPageWindow)
        self.widget.setGeometry(QtCore.QRect(300, 210, 500, 480))
        self.widget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget.setObjectName("widget")
        self.welcome_word = QtWidgets.QLabel(self.widget)
        self.welcome_word.setGeometry(QtCore.QRect(120, 20, 260, 40))
        self.welcome_word.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.welcome_word.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_word.setObjectName("welcome_word")
        self.login_input = QtWidgets.QLineEdit(self.widget)
        self.login_input.setGeometry(QtCore.QRect(95, 130, 360, 40))
        self.login_input.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.login_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.login_input.setObjectName("login_input")
        self.password_input = QtWidgets.QLineEdit(self.widget)
        self.password_input.setGeometry(QtCore.QRect(95, 190, 360, 40))
        self.password_input.setStyleSheet("background-color: rgb(242, 233, 228);\n"
"font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.error_label = QtWidgets.QLabel(self.widget)
        self.error_label.setGeometry(QtCore.QRect(105, 250, 290, 50))
        self.error_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(181, 131, 141);")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setWordWrap(True)
        self.error_label.setObjectName("error_label")
        self.user_icon = QtWidgets.QLabel(self.widget)
        self.user_icon.setGeometry(QtCore.QRect(45, 130, 40, 40))
        self.user_icon.setObjectName("user_icon")
        self.pass_icon = QtWidgets.QLabel(self.widget)
        self.pass_icon.setGeometry(QtCore.QRect(45, 190, 40, 40))
        self.pass_icon.setObjectName("pass_icon")
        self.regisrtation_button = QtWidgets.QPushButton(self.widget)
        self.regisrtation_button.setGeometry(QtCore.QRect(180, 350, 140, 40))
        self.regisrtation_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.regisrtation_button.setObjectName("regisrtation_button")
        self.back_button = QtWidgets.QPushButton(self.widget)
        self.back_button.setGeometry(QtCore.QRect(180, 400, 140, 40))
        self.back_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.back_button.setObjectName("back_button")

        self.retranslateUi(RegPageWindow)
        QtCore.QMetaObject.connectSlotsByName(RegPageWindow)

    def retranslateUi(self, RegPageWindow):
        _translate = QtCore.QCoreApplication.translate
        RegPageWindow.setWindowTitle(_translate("RegPageWindow", "BudgetKeeper"))
        self.logo_icon.setText(_translate("RegPageWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
        self.logo.setText(_translate("RegPageWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.welcome_word.setText(_translate("RegPageWindow", "Регистрация"))
        self.login_input.setPlaceholderText(_translate("RegPageWindow", " логин"))
        self.password_input.setPlaceholderText(_translate("RegPageWindow", " пароль"))
        self.user_icon.setText(_translate("RegPageWindow", "<html><head/><body><p><img src=\":/icons/user_icon.png\"/></p></body></html>"))
        self.pass_icon.setText(_translate("RegPageWindow", "<html><head/><body><p><img src=\":/icons/pass_icon.png\"/></p></body></html>"))
        self.regisrtation_button.setText(_translate("RegPageWindow", "Сохранить"))
        self.back_button.setText(_translate("RegPageWindow", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegPageWindow = QtWidgets.QWidget()
    ui = Ui_RegPageWindow()
    ui.setupUi(RegPageWindow)
    RegPageWindow.show()
    sys.exit(app.exec_())
