# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'success_delete_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuccessDeleteWindow(object):
    def setupUi(self, SuccessDeleteWindow):
        SuccessDeleteWindow.setObjectName("SuccessDeleteWindow")
        SuccessDeleteWindow.resize(500, 170)
        SuccessDeleteWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.confirm_label = QtWidgets.QLabel(SuccessDeleteWindow)
        self.confirm_label.setGeometry(QtCore.QRect(75, 30, 350, 110))
        self.confirm_label.setStyleSheet("font: 16pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.confirm_label.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_label.setWordWrap(True)
        self.confirm_label.setObjectName("confirm_label")

        self.retranslateUi(SuccessDeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(SuccessDeleteWindow)

    def retranslateUi(self, SuccessDeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        SuccessDeleteWindow.setWindowTitle(_translate("SuccessDeleteWindow", "BudgetKeeper"))
        self.confirm_label.setText(_translate("SuccessDeleteWindow", "<html><head/><body><p>Счёт был <span style=\" font-weight:600; color:#e5989b;\">успешно </span><span style=\" color:#22223b;\">удалён</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SuccessDeleteWindow = QtWidgets.QWidget()
    ui = Ui_SuccessDeleteWindow()
    ui.setupUi(SuccessDeleteWindow)
    SuccessDeleteWindow.show()
    sys.exit(app.exec_())
