# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_page_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WelcomePageWindow(object):
    def setupUi(self, WelcomePageWindow):
        WelcomePageWindow.setObjectName("WelcomePageWindow")
        WelcomePageWindow.resize(1100, 900)
        self.scrollArea = QtWidgets.QScrollArea(WelcomePageWindow)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1100, 900))
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1100, 1200))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(1160, 1231))
        self.scrollAreaWidgetContents.setToolTipDuration(0)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1100, 1200))
        self.widget_2.setObjectName("widget_2")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setGeometry(QtCore.QRect(175, 170, 750, 860))
        self.widget.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.widget.setObjectName("widget")
        self.anketa_word = QtWidgets.QLabel(self.widget)
        self.anketa_word.setGeometry(QtCore.QRect(80, 40, 590, 50))
        self.anketa_word.setStyleSheet("color: rgb(34, 34, 59);\n"
"font: 24pt \"Involve\";")
        self.anketa_word.setAlignment(QtCore.Qt.AlignCenter)
        self.anketa_word.setObjectName("anketa_word")
        self.next_button = QtWidgets.QPushButton(self.widget)
        self.next_button.setGeometry(QtCore.QRect(305, 780, 140, 40))
        self.next_button.setStyleSheet("border-radius: 15px;\n"
"font: 14pt \"Involve\";\n"
"background-color: rgb(34, 34, 59);\n"
"color: rgb(229, 152, 155);")
        self.next_button.setObjectName("next_button")
        self.info_label = QtWidgets.QLabel(self.widget)
        self.info_label.setGeometry(QtCore.QRect(100, 70, 550, 50))
        self.info_label.setStyleSheet("font: 12pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 130, 30, 30))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 30, 30))
        self.label_2.setObjectName("label_2")
        self.info_label_6 = QtWidgets.QLabel(self.widget)
        self.info_label_6.setGeometry(QtCore.QRect(90, 180, 590, 25))
        self.info_label_6.setStyleSheet("font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label_6.setWordWrap(True)
        self.info_label_6.setObjectName("info_label_6")
        self.info_label_7 = QtWidgets.QLabel(self.widget)
        self.info_label_7.setGeometry(QtCore.QRect(90, 130, 590, 25))
        self.info_label_7.setStyleSheet("font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label_7.setWordWrap(True)
        self.info_label_7.setObjectName("info_label_7")
        self.info_label_8 = QtWidgets.QLabel(self.widget)
        self.info_label_8.setGeometry(QtCore.QRect(40, 240, 670, 91))
        self.info_label_8.setStyleSheet("font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label_8.setWordWrap(True)
        self.info_label_8.setObjectName("info_label_8")
        self.info_label_9 = QtWidgets.QLabel(self.widget)
        self.info_label_9.setGeometry(QtCore.QRect(40, 320, 670, 430))
        self.info_label_9.setStyleSheet("font: 14pt \"Involve\";\n"
"color: rgb(34, 34, 59);")
        self.info_label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label_9.setWordWrap(True)
        self.info_label_9.setObjectName("info_label_9")
        self.info_label.raise_()
        self.anketa_word.raise_()
        self.next_button.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.info_label_6.raise_()
        self.info_label_7.raise_()
        self.info_label_8.raise_()
        self.info_label_9.raise_()
        self.logo = QtWidgets.QLabel(self.widget_2)
        self.logo.setGeometry(QtCore.QRect(90, 40, 240, 50))
        self.logo.setObjectName("logo")
        self.logo_icon = QtWidgets.QLabel(self.widget_2)
        self.logo_icon.setGeometry(QtCore.QRect(40, 40, 50, 50))
        self.logo_icon.setObjectName("logo_icon")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(WelcomePageWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomePageWindow)

    def retranslateUi(self, WelcomePageWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomePageWindow.setWindowTitle(_translate("WelcomePageWindow", "BudgetKeeper"))
        self.anketa_word.setText(_translate("WelcomePageWindow", "<html><head/><body><p><span style=\" color:#22223b;\">Добро пожаловать в </span><span style=\" color:#22223b;\">Budget</span><span style=\" color:#e5989b;\">Keeper</span></p></body></html>"))
        self.next_button.setText(_translate("WelcomePageWindow", "Вперёд"))
        self.label.setText(_translate("WelcomePageWindow", "<html><head/><body><p><img src=\":/icons/icon_ok_30x30.png\"/></p></body></html>"))
        self.label_2.setText(_translate("WelcomePageWindow", "<html><head/><body><p><img src=\":/icons/icon_ok_30x30.png\"/></p></body></html>"))
        self.info_label_6.setText(_translate("WelcomePageWindow", "<html><head/><body><p>Смотри <span style=\" font-weight:600; color:#e5989b;\">статистику</span> и <span style=\" font-weight:600; color:#e5989b;\">движение</span> денежных средств</p></body></html>"))
        self.info_label_7.setText(_translate("WelcomePageWindow", "<html><head/><body><p>Вноси <span style=\" font-weight:600; color:#e5989b;\">информацию</span> по своим счетам в конце месяца</p></body></html>"))
        self.info_label_8.setText(_translate("WelcomePageWindow", "<html><head/><body><p><span style=\" color:#22223b;\">Для начала работы тебе необходимо выбрать счета, информацию </span></p><p><span style=\" color:#22223b;\">по которым ты хочешь учитывать в приложении - от 1 до 10 счетов.</span></p></body></html>"))
        self.info_label_9.setText(_translate("WelcomePageWindow", "<html><head/><body><p align=\"justify\"><span style=\" color:#22223b;\">В приложении ты можешь выбрать следующие типы счетов:</span></p><p><span style=\" color:#22223b;\">- </span><span style=\" font-weight:600; color:#b5838d;\">карточный счёт</span><span style=\" color:#22223b;\"> - для отображения денежных средств на твоих картах;</span></p><p><span style=\" color:#22223b;\">- </span><span style=\" font-weight:600; color:#b5838d;\">текущий/резервный/накопительный счёт</span><span style=\" color:#22223b;\"> - для отображения денежных средств на счетах;</span></p><p><span style=\" color:#22223b;\">- </span><span style=\" font-weight:600; color:#b5838d;\">вклад</span><span style=\" color:#22223b;\"> - для отображения денежных средств, которые ты хранишь на вкладе;</span></p><p><span style=\" color:#22223b;\">- </span><span style=\" font-weight:600; color:#b5838d;\">валюта</span><span style=\" color:#22223b;\"> - для отображения денежных средств в $;</span></p><p><span style=\" color:#22223b;\">- </span><span style=\" font-weight:600; color:#b5838d;\">займ</span><span style=\" color:#22223b;\"> - для отображения денежных средств, которые ты выдал в долг.</span><br/></p><p><span style=\" color:#22223b;\">Определяйся со счетами и давай продолжим!</span></p></body></html>"))
        self.logo.setText(_translate("WelcomePageWindow", "<html><head/><body><p><img src=\":/logo/app_name_horizontal_350x50.png\"/></p></body></html>"))
        self.logo_icon.setText(_translate("WelcomePageWindow", "<html><head/><body><p><img src=\":/icons/logo_icon_50x50.png\"/></p></body></html>"))
import main_menu_logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomePageWindow = QtWidgets.QWidget()
    ui = Ui_WelcomePageWindow()
    ui.setupUi(WelcomePageWindow)
    WelcomePageWindow.show()
    sys.exit(app.exec_())
